### ISSUE TITLE
How did you create or find similarity.pkl?

### ISSUE THREAD

**Issue by EkimoCode** [anurag-b72/medicine-recommendation-system#1]
Hi, 

Great job, I love it.

I wonder how did you create the similarity.pkl, seems like that's the hard part.

Thank you

**Comment by anurag-b72** [comment]
Hi!
You should review [medicine-recommend.ipynb](https://github.com/anurag-b72/medicine-recommendation-system/blob/main/medicine-recommend.ipynb) once
