### ISSUE TITLE
Readme change request 

### ISSUE THREAD

**Issue by krishnaagarwal781** [anurag-b72/medicine-recommendation-system#2]
1.Clone Github Repository.
2.Extract pickle-files.rar it will extract "similarity.pkl" & "medicine_dict.pkl" pickle files. Make sure the files should be present in the root directory where the app.py is present 
3.Download Pycharm IDE and Open this application folder in it.
4.Open Termial.
5.Import Libraries: streamlit, pandas and pickle. That it run the commands in the terminal
 (i)pip install streamlit
6.After installation , then type- "streamlit run app.py"
7. if the application does not start then type python -m streamlit run app.py

**Comment by anurag-b72** [comment]
Thanks for notifying and updating this issue @krishnaagarwal781 :)
